import fs from 'fs';
import path from 'path';
import { Plugin } from '@obiemunoz/ts-migrate-server';

/**
 * The opening of every declaration file ts-migrate generates. A file that does
 * not start with it is somebody else's, so nothing rewrites it.
 */
export const GENERATED_MARKER = '// Generated by ts-migrate.';

/** Where a generated file named relative to the migration root sits on disk. */
export function generatedFilePath(rootDir: string, relativePath: string): string {
  return path.join(rootDir, ...relativePath.split('/'));
}

/**
 * What an earlier run declared in the file: nothing when no file is there yet,
 * and null when `parse` refuses the file that is. A refusal means a rewrite
 * would lose content, since it only keeps what `parse` reads back, so the
 * caller has to leave the file alone.
 */
export function readGeneratedDeclarations<T>(
  filePath: string,
  parse: (text: string) => T[] | null,
): T[] | null {
  let existingText: string | undefined;
  try {
    existingText = fs.readFileSync(filePath, 'utf-8');
  } catch {
    // No declaration file yet.
  }
  return existingText === undefined ? [] : parse(existingText);
}

/**
 * The plugin, doing one file's worth of work for the whole run and nothing on
 * the files after it: the evidence a declarations plugin writes out covers
 * every file already, and generating the file again per file would invalidate
 * the program each time.
 */
export function oncePerRun(plugin: Plugin<unknown>): Plugin<unknown> {
  let ran = false;
  return {
    ...plugin,
    run(params, lintConfig) {
      if (ran) return undefined;
      ran = true;
      return plugin.run(params, lintConfig);
    },
  };
}
