// HTMLElementTagNameMap from lib.dom.d.ts, split by whether the tag has an
// interface of its own. SVG tags, custom elements and the deprecated HTML tags
// JSX.IntrinsicElements still lists are absent, and fall back to any.
const specificElementTypesByTag: { [tag: string]: string } = {
  a: 'HTMLAnchorElement',
  area: 'HTMLAreaElement',
  audio: 'HTMLAudioElement',
  base: 'HTMLBaseElement',
  blockquote: 'HTMLQuoteElement',
  body: 'HTMLBodyElement',
  br: 'HTMLBRElement',
  button: 'HTMLButtonElement',
  canvas: 'HTMLCanvasElement',
  caption: 'HTMLTableCaptionElement',
  col: 'HTMLTableColElement',
  colgroup: 'HTMLTableColElement',
  data: 'HTMLDataElement',
  datalist: 'HTMLDataListElement',
  del: 'HTMLModElement',
  details: 'HTMLDetailsElement',
  dialog: 'HTMLDialogElement',
  div: 'HTMLDivElement',
  dl: 'HTMLDListElement',
  embed: 'HTMLEmbedElement',
  fieldset: 'HTMLFieldSetElement',
  form: 'HTMLFormElement',
  h1: 'HTMLHeadingElement',
  h2: 'HTMLHeadingElement',
  h3: 'HTMLHeadingElement',
  h4: 'HTMLHeadingElement',
  h5: 'HTMLHeadingElement',
  h6: 'HTMLHeadingElement',
  head: 'HTMLHeadElement',
  hr: 'HTMLHRElement',
  html: 'HTMLHtmlElement',
  iframe: 'HTMLIFrameElement',
  img: 'HTMLImageElement',
  input: 'HTMLInputElement',
  ins: 'HTMLModElement',
  label: 'HTMLLabelElement',
  legend: 'HTMLLegendElement',
  li: 'HTMLLIElement',
  link: 'HTMLLinkElement',
  map: 'HTMLMapElement',
  menu: 'HTMLMenuElement',
  meta: 'HTMLMetaElement',
  meter: 'HTMLMeterElement',
  object: 'HTMLObjectElement',
  ol: 'HTMLOListElement',
  optgroup: 'HTMLOptGroupElement',
  option: 'HTMLOptionElement',
  output: 'HTMLOutputElement',
  p: 'HTMLParagraphElement',
  picture: 'HTMLPictureElement',
  pre: 'HTMLPreElement',
  progress: 'HTMLProgressElement',
  q: 'HTMLQuoteElement',
  script: 'HTMLScriptElement',
  select: 'HTMLSelectElement',
  slot: 'HTMLSlotElement',
  source: 'HTMLSourceElement',
  span: 'HTMLSpanElement',
  style: 'HTMLStyleElement',
  table: 'HTMLTableElement',
  tbody: 'HTMLTableSectionElement',
  td: 'HTMLTableCellElement',
  template: 'HTMLTemplateElement',
  textarea: 'HTMLTextAreaElement',
  tfoot: 'HTMLTableSectionElement',
  th: 'HTMLTableCellElement',
  thead: 'HTMLTableSectionElement',
  time: 'HTMLTimeElement',
  title: 'HTMLTitleElement',
  tr: 'HTMLTableRowElement',
  track: 'HTMLTrackElement',
  ul: 'HTMLUListElement',
  video: 'HTMLVideoElement',
};

// Tags lib.dom.d.ts types as the base HTMLElement.
const plainElementTags = [
  'abbr',
  'address',
  'article',
  'aside',
  'b',
  'bdi',
  'bdo',
  'cite',
  'code',
  'dd',
  'dfn',
  'dt',
  'em',
  'figcaption',
  'figure',
  'footer',
  'header',
  'hgroup',
  'i',
  'kbd',
  'main',
  'mark',
  'nav',
  'noscript',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'search',
  'section',
  'small',
  'strong',
  'sub',
  'summary',
  'sup',
  'u',
  'var',
  'wbr',
];

export const elementTypesByTag: { [tag: string]: string | undefined } = {
  ...specificElementTypesByTag,
  ...Object.fromEntries(plainElementTags.map((tag) => [tag, 'HTMLElement'])),
};

