import fs from 'fs';
import path from 'path';
import ts from 'typescript';
import isDeclarationFile from './declarationFiles';
import { readText } from './readText';

interface EnsureAliasDeclarationsParams {
  rootDir: string;
  anyAlias?: string;
  anyFunctionAlias?: string;
  /** Compute the declaration file without writing it. */
  dryRun?: boolean;
}

const GENERATED_FILE = 'ts-migrate-aliases.d.ts';

/**
 * The declaration files the project's tsconfig includes, parsed, where a
 * pre-existing global alias declaration would live (e.g. Airbnb's shared
 * reactTypes.d.ts, pulled in through an extended config).
 */
function declarationSourceFiles(rootDir: string): ts.SourceFile[] {
  const configFile = path.join(rootDir, 'tsconfig.json');
  const { config, error } = ts.readConfigFile(configFile, ts.sys.readFile);
  if (error || !config) return [];
  const sourceFiles: ts.SourceFile[] = [];
  ts.parseJsonConfigFileContent(config, ts.sys, rootDir)
    .fileNames.filter(isDeclarationFile)
    .forEach((fileName) => {
      const text = readText(fileName);
      if (text === undefined) return;
      sourceFiles.push(ts.createSourceFile(fileName, text, ts.ScriptTarget.Latest));
    });
  return sourceFiles;
}

function isGlobalBlock(node: ts.Node): node is ts.ModuleDeclaration {
  return ts.isModuleDeclaration(node) && (node.flags & ts.NodeFlags.GlobalAugmentation) !== 0;
}

/**
 * Whether the file puts the alias in the global scope, which is where the
 * migrated annotations look for it.
 *
 * A declaration file with a top-level import or export is a module, so its own
 * declarations belong to the module and only a `declare global` block in it
 * reaches the global scope. TypeScript's `isFileForcedToBeModuleByFormat`
 * excludes declaration files, so the module-versus-script question for them is
 * decided by content rather than by extension.
 */
function declaresGlobalAlias(sourceFile: ts.SourceFile, name: string): boolean {
  const isAlias = (node: ts.Node) => ts.isTypeAliasDeclaration(node) && node.name.text === name;
  if (!ts.isExternalModule(sourceFile) && sourceFile.statements.some(isAlias)) return true;
  const inGlobalBlock = (node: ts.Node): boolean =>
    isGlobalBlock(node)
      ? node.body != null && ts.isModuleBlock(node.body) && node.body.statements.some(isAlias)
      : (ts.forEachChild(node, inGlobalBlock) ?? false);
  return ts.forEachChild(sourceFile, inGlobalBlock) ?? false;
}

/**
 * Writes an ambient declaration file for the requested aliases into rootDir,
 * where the tsconfig picks it up, so alias-annotated output compiles on
 * projects that don't declare the aliases themselves. Aliases some included
 * declaration file already declares globally are omitted (a second declaration
 * would be a duplicate identifier error), and an existing generated file is
 * kept as is. An alias a module exports rather than declares globally is
 * generated anyway: the export satisfies nothing the migrated files write,
 * since they name the alias without importing it, so the two end up as
 * separate symbols that happen to share a name. Returns the file written (with
 * its contents, so a dry run can hold it in memory instead), or null if
 * nothing needed to be written.
 */
export default function ensureAliasDeclarations({
  rootDir,
  anyAlias,
  anyFunctionAlias,
  dryRun,
}: EnsureAliasDeclarationsParams): { filePath: string; text: string } | null {
  const aliases = [
    ...(anyAlias ? [{ name: anyAlias, declaration: `type ${anyAlias} = any;` }] : []),
    ...(anyFunctionAlias
      ? [{ name: anyFunctionAlias, declaration: `type ${anyFunctionAlias} = (...args: any[]) => any;` }]
      : []),
  ];
  if (aliases.length === 0) return null;

  const targetFile = path.join(rootDir, GENERATED_FILE);
  if (fs.existsSync(targetFile)) return null;

  const declarations = declarationSourceFiles(rootDir);
  const missing = aliases.filter(
    ({ name }) => !declarations.some((sourceFile) => declaresGlobalAlias(sourceFile, name)),
  );
  if (missing.length === 0) return null;

  const text = `// Generated by ts-migrate. Global aliases used by the migrated annotations.\n${missing
    .map(({ declaration }) => declaration)
    .join('\n')}\n`;
  if (!dryRun) {
    fs.writeFileSync(targetFile, text);
  }
  return { filePath: targetFile, text };
}
