import fs from 'fs';
import path from 'path';
import ts from 'typescript';

interface EnsureAliasDeclarationsParams {
  rootDir: string;
  anyAlias?: string;
  anyFunctionAlias?: string;
  /** Compute the declaration file without writing it. */
  dryRun?: boolean;
}

const GENERATED_FILE = 'ts-migrate-aliases.d.ts';

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * The texts of the .d.ts files the project's tsconfig includes, where a
 * pre-existing global alias declaration would live (e.g. Airbnb's shared
 * reactTypes.d.ts, pulled in through an extended config).
 */
function declarationFileTexts(rootDir: string): string[] {
  const configFile = path.join(rootDir, 'tsconfig.json');
  const { config, error } = ts.readConfigFile(configFile, ts.sys.readFile);
  if (error || !config) return [];
  return ts
    .parseJsonConfigFileContent(config, ts.sys, rootDir)
    .fileNames.filter((fileName) => fileName.endsWith('.d.ts'))
    .map((fileName) => {
      try {
        return fs.readFileSync(fileName, 'utf-8');
      } catch {
        return '';
      }
    });
}

/**
 * Writes an ambient declaration file for the requested aliases into rootDir,
 * where the tsconfig picks it up, so alias-annotated output compiles on
 * projects that don't declare the aliases themselves. Aliases some included
 * .d.ts file already declares are omitted (a second declaration would be a
 * duplicate identifier error), and an existing generated file is kept as is.
 * Returns the file written (with its contents, so a dry run can hold it in
 * memory instead), or null if nothing needed to be written.
 */
export default function ensureAliasDeclarations({
  rootDir,
  anyAlias,
  anyFunctionAlias,
  dryRun,
}: EnsureAliasDeclarationsParams): { filePath: string; text: string } | null {
  const aliases = [
    ...(anyAlias ? [{ name: anyAlias, declaration: `type ${anyAlias} = any;` }] : []),
    ...(anyFunctionAlias
      ? [{ name: anyFunctionAlias, declaration: `type ${anyFunctionAlias} = (...args: any[]) => any;` }]
      : []),
  ];
  if (aliases.length === 0) return null;

  const targetFile = path.join(rootDir, GENERATED_FILE);
  if (fs.existsSync(targetFile)) return null;

  const declarationTexts = declarationFileTexts(rootDir);
  const missing = aliases.filter(
    ({ name }) =>
      !declarationTexts.some((text) => new RegExp(`\\btype\\s+${escapeRegExp(name)}\\b`).test(text)),
  );
  if (missing.length === 0) return null;

  const text = `// Generated by ts-migrate. Global aliases used by the migrated annotations.\n${missing
    .map(({ declaration }) => declaration)
    .join('\n')}\n`;
  if (!dryRun) {
    fs.writeFileSync(targetFile, text);
  }
  return { filePath: targetFile, text };
}
