import fs from 'fs';
import path from 'path';
import log from 'updatable-log';
import ts from 'typescript';
import { readText } from './readText';

/** Where the generated asset declarations live, relative to the migration root. */
export const ASSET_DECLARATIONS_FILE = 'types/ts-migrate-assets.d.ts';

const GENERATED_MARKER = '// Generated by ts-migrate.';

/**
 * Extensions whose default export is the asset's URL under every rule that
 * handles them: file-loader, url-loader, webpack 5 asset modules and the
 * presets built on those. `asset/inline` and url-loader below their size
 * limit produce a data URL, which is still a string.
 */
const URL_ASSET_EXTENSIONS = new Set([
  '.apng',
  '.avif',
  '.bmp',
  '.gif',
  '.ico',
  '.jpeg',
  '.jpg',
  '.png',
  '.webp',
  '.eot',
  '.otf',
  '.ttf',
  '.woff',
  '.woff2',
  '.aac',
  '.flac',
  '.m4a',
  '.mp3',
  '.mp4',
  '.ogg',
  '.wav',
  '.webm',
  '.pdf',
]);

/**
 * Packages that make an SVG import a React component instead of a URL. Their
 * absence is what settles `*.svg`: an SVG cannot become a component without
 * one of them installed.
 */
const SVG_COMPONENT_PACKAGES = [
  '@svgr/webpack',
  '@svgr/rollup',
  '@svgr/core',
  'vite-plugin-svgr',
  'svg-react-loader',
  'react-svg-loader',
  'babel-plugin-inline-react-svg',
];

const CODE_EXTENSION_REGEX = /^\.([cm]?[jt]sx?|json)$/;

/** What a `*.ext` pattern can be written for at all. */
const EXTENSION_REGEX = /^\.\w+$/;

export interface AssetPackageJson {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

/** How a project imports one extension, counted across its source files. */
interface AssetUsage {
  /** `import './App.css'`, which observes nothing the loader exports. */
  sideEffect: number;
  /** `import logo from './logo.png'` and `require('./logo.png')`. */
  default: number;
  /** `import { ReactComponent } from './logo.svg'` and namespace imports. */
  named: number;
}

/** The declaration shape chosen for one extension. */
type DeclarationKind = 'url' | 'sideEffect';

export interface DeclaredExtension {
  extension: string;
  kind: DeclarationKind;
}

export interface SkippedExtension {
  extension: string;
  reason: string;
}

export interface AssetDeclarations {
  filePath: string;
  text: string;
  declared: DeclaredExtension[];
  skipped: SkippedExtension[];
}

function usageFor(usage: Map<string, AssetUsage>, extension: string): AssetUsage {
  let entry = usage.get(extension);
  if (!entry) {
    entry = { sideEffect: 0, default: 0, named: 0 };
    usage.set(extension, entry);
  }
  return entry;
}

/**
 * The extension an import specifier asks a loader for, or null when the
 * specifier is not a relative path to a non-code file. Case is kept as
 * written: a `*.png` pattern does not match `./LOGO.PNG`.
 */
function assetExtension(specifier: string): string | null {
  if (!specifier.startsWith('./') && !specifier.startsWith('../')) return null;
  // Query and inline-loader syntax name something other than the file, and
  // neither is what a wildcard pattern matches.
  if (specifier.includes('?') || specifier.includes('!')) return null;
  const extension = path.extname(specifier);
  if (!EXTENSION_REGEX.test(extension) || CODE_EXTENSION_REGEX.test(extension.toLowerCase())) {
    return null;
  }
  return extension;
}

function recordImportDeclaration(usage: Map<string, AssetUsage>, node: ts.ImportDeclaration): void {
  if (!ts.isStringLiteralLike(node.moduleSpecifier)) return;
  const extension = assetExtension(node.moduleSpecifier.text);
  if (extension === null) return;
  const entry = usageFor(usage, extension);
  if (!node.importClause) {
    entry.sideEffect += 1;
  } else if (node.importClause.namedBindings) {
    entry.named += 1;
  } else {
    entry.default += 1;
  }
}

/**
 * How each asset extension is imported across the given source files. Only
 * the import form matters, so the files are parsed but never resolved.
 */
function collectAssetImports(files: string[]): Map<string, AssetUsage> {
  const usage = new Map<string, AssetUsage>();
  files.forEach((file) => {
    const text = readText(file);
    if (text === undefined) return;
    // JSX kind so application files parse cleanly; plain JS parses the same.
    const sourceFile = ts.createSourceFile(
      file,
      text,
      ts.ScriptTarget.Latest,
      false,
      ts.ScriptKind.JSX,
    );
    const visit = (node: ts.Node) => {
      if (ts.isImportDeclaration(node)) {
        recordImportDeclaration(usage, node);
      } else if (ts.isExportDeclaration(node)) {
        // `export { x } from './logo.svg'` republishes the loader's exports.
        if (node.moduleSpecifier && ts.isStringLiteralLike(node.moduleSpecifier)) {
          const extension = assetExtension(node.moduleSpecifier.text);
          if (extension !== null) usageFor(usage, extension).named += 1;
        }
      } else if (ts.isCallExpression(node)) {
        const [firstArgument] = node.arguments;
        const isModuleCall =
          node.expression.kind === ts.SyntaxKind.ImportKeyword ||
          (ts.isIdentifier(node.expression) && node.expression.text === 'require');
        if (isModuleCall && firstArgument && ts.isStringLiteralLike(firstArgument)) {
          const extension = assetExtension(firstArgument.text);
          if (extension !== null) usageFor(usage, extension).default += 1;
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(sourceFile);
  });
  return usage;
}

function hasDependency(packageJson: AssetPackageJson | null, name: string): boolean {
  if (!packageJson) return false;
  return [packageJson.dependencies, packageJson.devDependencies].some(
    (dependencies) =>
      typeof dependencies === 'object' && dependencies !== null && name in dependencies,
  );
}

/**
 * The declaration for one extension, or the reason there is none.
 *
 * A declaration that is wrong is worse than none at all: the suppression it
 * replaces is visibly unfinished, while a wrong shape type-checks. So an
 * extension is only declared where its type cannot depend on the loader.
 *
 * - Imported for its side effects alone, the module's exports are never
 *   observed, so a module with no exports is true whatever the loader does.
 *   That is also the only form TypeScript 6 reports (TS2882); 5.x lets an
 *   unresolved side-effect import through silently.
 * - A default import of an image, font or media file is its URL under every
 *   rule that handles those.
 * - A named import means the loader publishes named exports, and only the
 *   loader knows what they are.
 * - Anything else (stylesheets bound to a name, YAML, GraphQL, Markdown)
 *   has a shape the loader decides, so it keeps its suppression.
 */
function declarationFor(
  extension: string,
  usage: AssetUsage,
  packageJson: AssetPackageJson | null,
): DeclaredExtension | SkippedExtension {
  if (usage.named > 0) {
    return {
      extension,
      reason: 'imported by name, so the loader decides what it exports',
    };
  }
  if (usage.default === 0) {
    return { extension, kind: 'sideEffect' };
  }
  const lower = extension.toLowerCase();
  if (lower === '.svg') {
    const svgr = SVG_COMPONENT_PACKAGES.find((name) => hasDependency(packageJson, name));
    return svgr === undefined
      ? { extension, kind: 'url' }
      : { extension, reason: `${svgr} can make it a component rather than a URL` };
  }
  if (URL_ASSET_EXTENSIONS.has(lower)) {
    return { extension, kind: 'url' };
  }
  return { extension, reason: 'the value it exports depends on the loader' };
}

function isDeclared(entry: DeclaredExtension | SkippedExtension): entry is DeclaredExtension {
  return 'kind' in entry;
}

function renderAssetDeclarations(declared: DeclaredExtension[]): string {
  const blocks = [...declared]
    .sort((a, b) => a.extension.localeCompare(b.extension))
    .map(({ extension, kind }) =>
      kind === 'url'
        ? `declare module '*${extension}' {\n  const src: string;\n  export default src;\n}\n`
        : `declare module '*${extension}' {}\n`,
    );
  return [
    `${GENERATED_MARKER} Wildcard declarations for the asset imports the`,
    '// bundler resolves and TypeScript does not, so they type instead of',
    '// collecting a suppression at every import site.',
    '// Only the extensions this project imports are listed, and only where no',
    '// loader can change the type. An extension imported by name, or a style',
    '// sheet bound to a name, is left out: only its loader knows what those',
    '// export. Declare them in a file of your own.',
    '',
    ...blocks,
  ].join('\n');
}

/**
 * The wildcard declarations for a project's asset imports, or null when it
 * has none to declare.
 */
export function buildAssetDeclarations(
  rootDir: string,
  files: string[],
  packageJson: AssetPackageJson | null,
): AssetDeclarations | null {
  const usage = collectAssetImports(files);
  const entries = [...usage]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([extension, extensionUsage]) =>
      declarationFor(extension, extensionUsage, packageJson),
    );
  const declared = entries.filter(isDeclared);
  const skipped = entries.filter((entry): entry is SkippedExtension => !isDeclared(entry));
  if (declared.length === 0 && skipped.length === 0) return null;

  return {
    filePath: path.join(rootDir, ...ASSET_DECLARATIONS_FILE.split('/')),
    text: renderAssetDeclarations(declared),
    declared,
    skipped,
  };
}

function describe(extensions: string[]): string {
  return extensions.map((extension) => `*${extension}`).join(', ');
}

/**
 * Writes the declarations and reports both halves of the decision. A file at
 * that path ts-migrate did not write is the user's, so it is left alone.
 */
export function writeAssetDeclarations(declarations: AssetDeclarations): void {
  const { filePath, text, declared, skipped } = declarations;
  skipped.forEach(({ extension, reason }) => {
    log.info(`Leaving *${extension} imports undeclared: ${reason}.`);
  });
  if (declared.length === 0) return;

  // Undefined when there is no declaration file yet.
  const existing = readText(filePath);
  if (existing !== undefined && !existing.startsWith(GENERATED_MARKER)) {
    log.warn(`${filePath} already exists and ts-migrate did not write it, so it is left alone.`);
    return;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, text);
  log.info(
    `Declared ${describe(declared.map(({ extension }) => extension))} in ${filePath}, so those ` +
      'imports type instead of collecting a suppression.',
  );
}
