import fs from 'fs';
import path from 'path';
import report from '../../../commands/report';
import {
  formatTypeDebtReport,
  formatTypeDebtSummary,
  scanTypeDebt,
} from '../../../utils/typeDebt';
import { createDir, deleteDir } from '../../test-utils';

jest.mock('updatable-log', () => {
  // eslint-disable-next-line global-require
  const { noopUpdatableLog } = require('../../test-utils');
  return noopUpdatableLog();
});

function writeFiles(rootDir: string, files: Record<string, string>) {
  Object.entries(files).forEach(([relativePath, content]) => {
    const absolutePath = path.join(rootDir, relativePath);
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    fs.writeFileSync(absolutePath, content);
  });
}

const aliasDeclarations = `// Generated by ts-migrate. Global aliases used by the migrated annotations.
type $TSFixMe = any;
type $TSFixMeFunction = (...args: any[]) => any;
`;

const fileWithDebt = `// @ts-expect-error TS(2304) FIXME: Cannot find name 'foo'.
foo();
// @ts-ignore manual note
bar();
const s = 'not a real @ts-expect-error directive';
const t = \`template
@ts-ignore spanning lines\`;
const x: $TSFixMe = 1;
const f: $TSFixMeFunction = () => {};
function g(a: any): any {
  return a;
}
const arr: any[] = [];
export default { s, t, x, f, g, arr };
`;

const tsxFileWithDebt = `import React from 'react';

export default function B() {
  return (
    <div>
      {/* @ts-expect-error TS(2322) FIXME: Type 'number' is not assignable */}
      <span data-x={1 as any}>plain @ts-ignore text stays text</span>
    </div>
  );
}
`;

function writeProject(rootDir: string) {
  writeFiles(rootDir, {
    'tsconfig.json': '{ "compilerOptions": {} }',
    'ts-migrate-aliases.d.ts': aliasDeclarations,
    'src/a.ts': fileWithDebt,
    'src/b.tsx': tsxFileWithDebt,
    'src/clean.ts': 'export const n: number = 1;\n',
  });
}

describe('type debt scanner', () => {
  let rootDir: string;
  beforeEach(() => {
    rootDir = createDir();
  });

  afterEach(() => {
    deleteDir(rootDir);
  });

  it('counts suppressions, aliases, and explicit any per file', () => {
    writeProject(rootDir);

    const debt = scanTypeDebt(rootDir);

    expect(debt.filesScanned).toBe(3);
    expect(debt.aliasNames).toEqual(['$TSFixMe', '$TSFixMeFunction']);
    expect(Object.keys(debt.files)).toEqual(['src/a.ts', 'src/b.tsx']);
    expect(debt.files['src/a.ts']).toEqual({
      tsExpectError: 1,
      tsIgnore: 1,
      anyAlias: 2,
      any: 3,
      codes: { TS2304: 1 },
    });
    expect(debt.files['src/b.tsx']).toEqual({
      tsExpectError: 1,
      tsIgnore: 0,
      anyAlias: 0,
      any: 1,
      codes: { TS2322: 1 },
    });
    expect(debt.totals).toEqual({
      tsExpectError: 2,
      tsIgnore: 1,
      anyAlias: 2,
      any: 4,
      codes: { TS2304: 1, TS2322: 1 },
    });
  });

  it('discovers alias names from project declarations instead of hardcoding them', () => {
    writeFiles(rootDir, {
      'tsconfig.json': '{ "compilerOptions": {} }',
      'globals.d.ts': [
        'type Loose = any;',
        'type NotAnAlias = string;',
        'interface Shape { x: number }',
        '',
      ].join('\n'),
      'a.ts': "const v: Loose = 1;\nconst w: NotAnAlias = 's';\nexport default { v, w };\n",
      // $TSFixMe is not declared in this project, so it is not an alias here.
      'b.ts': 'declare const u: $TSFixMe;\nexport default u;\n',
    });

    const debt = scanTypeDebt(rootDir);

    expect(debt.aliasNames).toEqual(['Loose']);
    expect(Object.keys(debt.files)).toEqual(['a.ts']);
    expect(debt.files['a.ts']).toMatchObject({ anyAlias: 1, any: 0 });
  });

  it('formats the report and the one-paragraph summary', () => {
    writeProject(rootDir);

    const debt = scanTypeDebt(rootDir);
    const reportText = formatTypeDebtReport(debt, 'frontend/foo');
    expect(reportText).toContain('Type debt report for frontend/foo (3 files scanned)');
    expect(reportText).toContain('@ts-expect-error comments: 2');
    expect(reportText).toContain('any-alias annotations ($TSFixMe, $TSFixMeFunction): 2');
    expect(reportText).toContain('TS2304 x1');
    expect(reportText).toContain('uncoded x1');
    expect(reportText).toContain('src/a.ts (1 @ts-expect-error, 1 @ts-ignore, 2 any-alias, 3 any)');

    const summary = formatTypeDebtSummary(debt, 'frontend/foo');
    expect(summary).toContain('3 suppression comments (2 @ts-expect-error, 1 @ts-ignore)');
    expect(summary).toContain('2 any-alias annotations');
    expect(summary).toContain('4 explicit any');
    expect(summary).toContain('in 2 of 3 files');
    expect(summary).toContain('ts-migrate report frontend/foo');
  });

  it('reports no debt for a clean project', () => {
    writeFiles(rootDir, {
      'tsconfig.json': '{ "compilerOptions": {} }',
      'a.ts': 'export const n: number = 1;\n',
    });

    const debt = scanTypeDebt(rootDir);
    expect(debt.totals).toEqual({ tsExpectError: 0, tsIgnore: 0, anyAlias: 0, any: 0, codes: {} });
    expect(formatTypeDebtReport(debt, 'foo')).toContain(
      'No suppression comments or any-type annotations found.',
    );
    expect(formatTypeDebtSummary(debt, 'foo')).toBe('Type debt: none (1 files scanned).');
  });
});

describe('report command', () => {
  let rootDir: string;
  beforeEach(() => {
    rootDir = createDir();
  });

  afterEach(() => {
    deleteDir(rootDir);
  });

  it('returns 0 and prints JSON with --json', () => {
    writeProject(rootDir);

    const chunks: string[] = [];
    const spy = jest.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      chunks.push(String(chunk));
      return true;
    });
    const exitCode = report({ rootDir, folder: 'frontend/foo', json: true });
    spy.mockRestore();

    expect(exitCode).toBe(0);
    const parsed = JSON.parse(chunks.join(''));
    expect(parsed.filesScanned).toBe(3);
    expect(parsed.totals.any).toBe(4);
    expect(parsed.files['src/a.ts'].codes).toEqual({ TS2304: 1 });
  });

  it('returns nonzero when the folder has no tsconfig', () => {
    expect(report({ rootDir, folder: 'foo' })).toBe(-1);
  });
});
